build:
  maxIssues: 0

complexity:
  active: true
  LongMethod:
    threshold: 200
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 12
  CyclomaticComplexMethod:
    threshold: 50
  TooManyFunctions:
    thresholdInClasses: 100
    thresholdInObjects: 20
  LargeClass:
    threshold: 3000
  ComplexCondition:
    threshold: 5
  NestedBlockDepth:
    threshold: 8

style:
  active: true
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140
  ReturnCount:
    max: 15
  FunctionOnlyReturningConstant:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  UseRequire:
    active: true
  UnusedPrivateMember:
    active: false

naming:
  active: true
  FunctionNaming:
    ignoreAnnotated:
      - Composable

empty-blocks:
  active: true

comments:
  active: false

performance:
  active: true

coroutines:
  active: true

exceptions:
  active: true
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false
