build:
  maxIssues: 0

formatting:
  active: false

complexity:
  active: true
  LongMethod:
    threshold: 60
  LongParameterList:
    threshold: 6
  ComplexMethod:
    threshold: 15

style:
  active: true
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignorePropertyDeclaration: true
    ignoreAnnotation: true

naming:
  active: true

potential-bugs:
  active: true

performance:
  active: true
