name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  format:
    name: Check Formatting
    uses: ./.github/workflows/_format.yml

  copyright:
    name: Check Copyright Headers
    uses: ./.github/workflows/_copyright.yml

  test:
    name: Unit Tests
    needs: [format, copyright]
    uses: ./.github/workflows/_test.yml

  coverage:
    name: Test Coverage
    needs: [format, copyright]
    uses: ./.github/workflows/_coverage.yml

  docs:
    name: Documentation
    needs: [format, copyright]
    uses: ./.github/workflows/_docs.yml

  build-library:
    name: Build Library
    needs: [format, copyright, test, coverage, docs]
    uses: ./.github/workflows/_build-library.yml

  build-examples:
    name: Build Examples
    needs: [format, copyright, test, coverage, docs]
    uses: ./.github/workflows/_build-examples.yml

  instrumented-test:
    name: Instrumentation Tests (PR only)
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_instrumentation.yml

