name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  format:
    name: Check Formatting
    uses: ./.github/workflows/_format.yml

  test:
    name: Unit Tests
    needs: format
    uses: ./.github/workflows/_test.yml

  build-library:
    name: Build Library
    needs: [format, test]
    uses: ./.github/workflows/_build-library.yml

  build-examples:
    name: Build Examples
    needs: [format, test]
    uses: ./.github/workflows/_build-examples.yml

